### ISSUE TITLE
Reviewed 3 main Issues found on this project. Morning Session teams' comment.

### ISSUE THREAD

**Issue by HERMON-1995** [AmineDerbal/portfolio-bootstrap#1]
Hey [AmineDerbal],

Great work on making good responsive design using Bootstrap framework👏
You've done well building portfolio website for desktop version using bootstrap framework, but there are still some which aren't addressed yet.

STATUS: REQUEST CHANGES ♻️

  > You should not use breakpoints in the desktop version when using Bootstrap framework, in order to follow up the instructions.  
  > Kindly use justify-content-center class to make your items centralized in the header section.

**Comment by AmineDerbal** [comment]
Thanks for your feedback
